task_8.4_rev0
pietryczko/kodilla-course pull request #22
Opened 2022-08-30 12:23 UTC by pietryczko

2022-08-31 06:45 UTC, MARudnicki requested changes

2022-08-31 06:45 UTC, MARudnicki commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightFinder.java
> +        flights.put("Moscow", true);
Mapa lotnisk nie powinna byc budowana przy kazdym wywolaniu metody. To nieefektywne. Zbuduj ja w konstruktorze

2022-08-31 06:45 UTC, MARudnicki commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightFinder.java
> +            }
Lapiesz tutaj tylko 2 case, a powinny byc 3
- lotnisko nie istnieje
- istnieje i jest dostepne (true)
- istnieje i nie jest dostepne

2022-09-01 07:00 UTC, MR-testaccount requested changes

2022-09-01 07:00 UTC, MR-testaccount commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightFinder.java
> +        boolean flightIsAva = flights.get(flight.getArrivalAirport());
ta nazwa jest do poprawy

2022-09-01 07:00 UTC, MR-testaccount commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightFinder.java
> +
zbedne spacje do usuniecia

2022-09-01 07:00 UTC, MR-testaccount commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightFinder.java
> +
zbedne spacje do usuniecia

2022-09-09 11:11 UTC, merged